<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />
	<Import Project="..\..\..\packing.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
		<ProjectReference Include="..\Syrna.TemplateProject.Application.Contracts\Syrna.TemplateProject.Application.Contracts.csproj" />
	</ItemGroup>

</Project>
