<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Syrna.TemplateProject</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Syrna.TemplateProject.Application\Syrna.TemplateProject.Application.csproj" />
    <ProjectReference Include="..\Syrna.TemplateProject.Domain.Tests\Syrna.TemplateProject.Domain.Tests.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

</Project>
