<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Syrna.TemplateProject</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="EphemeralMongo.Core" />
    <PackageReference Include="EphemeralMongo6.runtime.linux-x64" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />
    <PackageReference Include="EphemeralMongo6.runtime.osx-x64" Condition="$([MSBuild]::IsOSPlatform('OSX'))" />
    <PackageReference Include="EphemeralMongo6.runtime.win-x64" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
    <ProjectReference Include="..\..\src\Syrna.TemplateProject.MongoDB\Syrna.TemplateProject.MongoDB.csproj" />
    <ProjectReference Include="..\Syrna.TemplateProject.TestBase\Syrna.TemplateProject.TestBase.csproj" />
  </ItemGroup>

</Project>
