<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\..\common.props" />
	<Import Project="..\..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<RootNamespace>Syrna.TemplateProject.MainDemo.SqlServer</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="EntityFrameworkCore\TemplateProjectEfCoreEntityExtensionMappings.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Syrna.TemplateProject.MainDemo.Domain\Syrna.TemplateProject.MainDemo.Domain.csproj" />
		<ProjectReference Include="..\Syrna.TemplateProject.MainDemo.EntityFrameworkCore\Syrna.TemplateProject.MainDemo.EntityFrameworkCore.csproj" />
		
		<PackageReference Include="Volo.Abp.EntityFrameworkCore.SqlServer" />
		
		<PackageReference Include="Volo.Abp.SettingManagement.EntityFrameworkCore" />
		<PackageReference Include="Volo.Abp.AuditLogging.EntityFrameworkCore" />
		<PackageReference Include="Volo.Abp.TenantManagement.EntityFrameworkCore" />
		<PackageReference Include="Volo.Abp.FeatureManagement.EntityFrameworkCore" />
		<PackageReference Include="Volo.Abp.PermissionManagement.EntityFrameworkCore" />
		<PackageReference Include="Volo.Abp.Identity.EntityFrameworkCore" />
		<PackageReference Include="Volo.Abp.OpenIddict.EntityFrameworkCore" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
